export const LOGOUT = 'LOGOUT';

// get the person profile action constants
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const SET_TOKEN = 'SET_TOKEN';

// all need atten events action constants
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

export const GET_ACTIVE_EVENTS = 'GET_ACTIVE_EVENTS';
export const GET_ACTIVE_EVENTS_SUCCESS = 'GET_ACTIVE_EVENTS_SUCCESS';
export const GET_ACTIVE_EVENTS_ERROR = 'GET_ACTIVE_EVENTS_ERROR';

// get the single attend action constants
export const GET_SINGLE_EVENT = 'GET_SINGLE_EVENT';
export const GET_SINGLE_EVENT_SUCCESS = 'GET_SINGLE_EVENT_SUCCESS';
export const GET_SINGLE_EVENT_ERROR = 'GET_SINGLE_EVENT_ERROR';

// get the single news action constants
export const GET_SINGLE_NEWS = 'GET_SINGLE_NEWS';
export const GET_SINGLE_NEWS_SUCCESS = 'GET_SINGLE_NEWS_SUCCESS';
export const GET_SINGLE_NEWS_ERROR = 'GET_SINGLE_NEWS_ERROR';

// get all news action constants
export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';

// export const GET_STORAGE_DATA = 'GET_STORAGE_DATA';
// export const GET_STORAGE_DATA_SUCCESS = 'GET_STORAGE_DATA_SUCCESS';
// export const GET_STORAGE_DATA_FAILURE = 'GET_STORAGE_DATA_FAILURE';

export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const ANSWER_QUESTION_SUCCESS = 'ANSWER_QUESTION_SUCCESS';
export const ANSWER_QUESTION_ERROR = 'ANSWER_QUESTION_ERROR';

export const INCREMENT_NOW_INDEX = 'INCREMENT_NOW_INDEX';
export const CLEAR_EVERY_TERM_ANSWER_COUNT = 'CLEAR_EVERY_TERM_ANSWER_COUNT';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const FEEDBACK = 'FEEDBACK';
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const FEEDBACK_ERROR = 'FEEDBACK_ERROR';

export const ATTEND = 'ATTEND';
export const ATTEND_SUCCESS = 'ATTEND_SUCCESS';
export const ATTEND_ERROR = 'ATTEND_ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

// initial sign state
export const INITIAL_SIGN_STATE = 'INITIAL_SIGN_STATE';